#!/bin/bash

SELF_DIR="$(dirname $BASH_SOURCE)"
SELF_NAME="$(basename $BASH_SOURCE)"

SRC_BRANCH=dev
DEST_BRANCH=swiftpm

_generate() {
    git add .
}

. "$SELF_DIR/_generate" gyb -p LICENSE CHANGELOG.md Package.swift
