#!/bin/bash

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
ROOT="$(git rev-parse --show-toplevel)"
CWD="$(pwd)"

SOURCE_BRANCH='dev'
DESTINATION_BRANCH='swiftpm'

cd "$ROOT"

test "$(git status --porcelain)" && DIRTY=1 || DIRTY=
[ "$DIRTY" ] && git stash save -a -q
if [ "$BRANCH" != $SOURCE_BRANCH ]
then
    git checkout -q $SOURCE_BRANCH
fi
./configure
make -s gyb
rm -rf configure Makefile Utils
git add Sources
git stash save -q
if [ -n "$(git rev-parse -q --verify $DESTINATION_BRANCH)" ]
then
    git checkout -q $DESTINATION_BRANCH
else
    git checkout -q --orphan $DESTINATION_BRANCH
fi
git reset -q
git clean -dfxq
git stash pop -q
SRCS="$(git ls-tree -r --name-only $SOURCE_BRANCH Sources | sed '/\.gyb$/d')"
git checkout $SOURCE_BRANCH LICENSE Package.swift "$SRCS"
git add .
git commit -m "compile $(git rev-parse $SOURCE_BRANCH) for $DESTINATION_BRANCH"
git checkout -q $BRANCH
git reset -q
git clean -dfxq
git checkout -q -- .
[ "$DIRTY" ] && git stash pop -q

cd "$CWD"
