#!/bin/bash

SELF_DIR="$(dirname $BASH_SOURCE)"
SELF_NAME="$(basename $BASH_SOURCE)"

SRC_BRANCH=dev
DEST_BRANCH=swiftpm

. "$SELF_DIR/_generate-init" gyb -p LICENSE Package.swift

git add .

. "$SELF_DIR/_generate-fine"
