#!/bin/bash

SELF_DIR="$(dirname $BASH_SOURCE)"
SELF_NAME="$(basename $BASH_SOURCE)"

SRC_BRANCH=dev
DEST_BRANCH=cocoapods

if [ -z "$VERSION" ]
then
    VERSION="$1"
fi

if [ -z "$VERSION" ]
then
    >&2 echo "usage:  $SELF_NAME <VERSION>"
    exit 1
fi

_generate() {
    __genspec() {
        echo "Pod::Spec.new do |spec|"
        STATE=
        while [ $# -gt 0 ]
        do
            case "$1" in
            -*)
                STATE="${1:1}"
                if [[ "$STATE" == *deployment-target ]]
                then
                    STATE="${STATE/-/.}"
                fi
                STATE="${STATE//-/_}"
                shift
                case "$STATE" in
                -|'')
                    ;;
                authors)
                    AUTHORS_COUNT=0
                    for arg in "$@"
                    do
                        if [[ "$arg" == -* ]]
                        then
                            break
                        fi
                        ((AUTHORS_COUNT++))
                    done
                    echo "  spec.$STATE = {"
                    for i in "$(seq 1 $AUTHORS_COUNT)"
                    do
                        echo -n "    \"${1% *}\" => \"${1##* }\""
                        if [ $i -ne $AUTHORS_COUNT ]
                        then
                            echo ,
                        else
                            echo
                        fi
                    done
                    echo '  }'
                    ;;
                license)
                    echo "  spec.$STATE = {"
                    echo "    :type => \"$1\""
                    echo '  }'
                    ;;
                source)
                    echo "  spec.$STATE = {"
                    echo -n "    :${1%% *} => \"${1#* }\""
                    case "${1%% *}" in
                    git|svn)
                        echo ,
                        echo '    :tag => "v#{spec.version}"'
                        ;;
                    hg)
                        echo ,
                        echo '    :revision => "v#{spec.version}"'
                        ;;
                    *)
                        echo
                        ;;
                    esac
                    echo '  }'
                    ;;
                *)
                    echo "  spec.$STATE = \"$1\""
                    ;;
                esac
                ;;
            esac
            shift
        done
        echo end
    }
    __genspec -name AAA -version "$VERSION" -authors 'Mayu Laierlence minacle@live.com' -social-media-url https://twitter.com/mlrlnc -license MIT -homepage https://github.com/minacle/AAA -source 'git https://github.com/minacle/AAA.git' -source-files 'Sources/**/*.swift' -summary 'An Any Accessory' -ios-deployment-target 8.0 -osx-deployment-target 10.10 -tvos-deployment-target 9.0 -watchos-deployment-target 2.0 >AAA.podspec
    git add .
}

. "$SELF_DIR/_generate" gyb -p LICENSE
