#!/bin/bash

SELF_DIR="$(dirname $BASH_SOURCE)"
SELF_NAME="$(basename $BASH_SOURCE)"

SRC_BRANCH=dev
DEST_BRANCH=carthage

_generate() {
    git add .
    carthage build --no-skip-current >/dev/null
    carthage archive >/dev/null
}

. "$SELF_DIR/_generate" xcodeproj -k AAA.xcodeproj -p LICENSE -s AAA.framework.zip
